export const GET_AGGREGATE_PROPERTIES = 'GET_AGGREGATE_PROPERTIES';
export const GET_AUTH_TOKEN = 'GET_AUTH_TOKEN';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_FILES = 'GET_FILES';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_SELECTED_FILE = 'SET_SELECTED_FILE';
